### ISSUE TITLE
Stables spawning all the way at the bottom of the void.

### ISSUE THREAD

**Issue by dalekfan** [Sharffffff/Mantori#1]
I don't know what's causing this. My best guess is it's conflicts with the enderscape mod? Every stable I've teleported to has been all the way down in the void, like this.
![2022-06-06_13 03 34](https://user-images.githubusercontent.com/49622705/172209840-11afa54d-0ceb-4daa-b0d4-cd429ec26c79.png)

**Comment by Sharffffff** [comment]
It is a known bug, currently working on fixing it. Exists because of the incorrect structure type currently used for the stables generation.

**Comment by Sharffffff** [comment]
Should be fixed in the next release of the mod, thankfully 1.19 fixed this issue for me :D
