### ISSUE TITLE
1.19: Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by Thatsmusic99** [Sharffffff/Mantori#10]
The paste for the crash in question is here: https://paste.gg/p/anonymous/340e024dfd604657b354259ed672405d

Using version 1.1.1 of the mod on version 1.19, 0.14.8. I'm afraid I'm not entirely sure what was happening at the time when the server itself crashed.

**Comment by Sharffffff** [comment]
I thought that maybe newer version of fabric has changed "Random" once again, but no, it's the same. This is strange, it works for me with newest fabric / fabric api / bclib. So I am absolutely not sure what's going on there. Did you download the mod from CurseForge or Modrinth? On CurseForge it works fine, so maybe I somehow uploaded a wrong file to Modrinth?

**Comment by Thatsmusic99** [comment]
That's a good question, but the modpack at hand being used is Medieval Minecraft v5 for Fabric, which I assume uses the Curseforge version.

I reviewed the log file generated before the crash and won't send the full thing, but I noticed the errors in full here stating the server was failing to light chunks: https://paste.gg/p/anonymous/2b68d7219f3c458387ba8991dd5f368b - real shot in the dark that I'm doubtful about, could it be related to Starlight, since I'm aware it overhauls the light generation? I don't remember it doing any strange thread work though.

**Comment by Sharffffff** [comment]
I know what is the problem, but it is an nonexistent problem. Problem is in Variants using old Random class, which was changed in 1.19 - but! But it is changed in my mod's 1.1.1 version. So I honestly have no idea why it thinks it is legacy option, when it's using new one.

**Comment by Thatsmusic99** [comment]
Ah the joys of mod development

**Comment by Thatsmusic99** [comment]
So, just an update on this, it seems like it's an issue not limited to the mod. I've checked our most recent crash reports surrounding the issue and whenever the error pops up, it seems to switch between Minecraft itself, Mantori/Aphid Additions and Immersive Weathering. However, this does not imply that there is a conflict. Quite honestly, I'm not entirely sure what it is myself. I'll take this into my own hands. 

I appreciate the insight regardless and best of luck going forward with your mod!
