### ISSUE TITLE
we spoke on curse:

### ISSUE THREAD

**Issue by Loh-key** [Sharffffff/Mantori#5]
[latest.log](https://github.com/Sharffffff/Mantori/files/9077823/latest.log)

**Comment by Sharffffff** [comment]
Can you provide crash log too, please?

**Comment by Sharffffff** [comment]
Also, your log shows that you do not, in fact, have BetterEnd installed

**Comment by Loh-key** [comment]
ok so it was a whole s***show that caused all of this, none of it was from your mod.  In the crash report I did not have betterend, as I was struggling with issues on their end.  Now that I've solved that, your mod is working fine, and was not the cause of the crash at any point. Cheers for checking.
