### ISSUE TITLE
Not sure what the problem is?

### ISSUE THREAD

**Issue by Loh-key** [Sharffffff/Mantori#6]
Hi it's me again.  Got the stuff with BetterEnd/BetterNether figured out on my end, both are working perfectly.  So I say, time to finally add Aphid, the reason I started this journey in the first place!! 

Still crashing.  Wish I knew anything about code so I could try to decipher and help, but alas, I am the worst type of end user haha
[latest.log](https://github.com/Sharffffff/Mantori/files/9087744/latest.log)

**Comment by Loh-key** [comment]
nope both versions of geckolib for 1.19 crashing

**Comment by Sharffffff** [comment]
Are you using fabric version of geckolib? Also, it looks like issue is caused by conflict between vanilla tweaks and geckolib, try removing vanilla tweaks and see if it still crashes. And provide both latest log and crash log if it does.

**Comment by Loh-key** [comment]
I would give you the crash log if it gave it to me when using your mod, I get exit-code:-1 or whatever the null field is called which is why I always resort to giving you latest.  

I feel like I haven't actually played this game in 3 days, so with BetterEnd finally working, I'm gonna go enjoy my night off and explore :P I'll get back to ya on this stuff tomorrow, cheers for the help so far <3
