### ISSUE TITLE
Target Fabric API 0.56.0 on 1.18.2 for compatibility with Quilted Fabric API

### ISSUE THREAD

**Issue by erisdev** [Sharffffff/Mantori#8]
It doesn't seem like you're using any features specific to 0.57.0. I changed the version number in `fabric.mod.json` and it works without a hitch.

Also, not an issue, but I love the critter design. Chalicothere bugs... I've never seen a knuckle walking insect before!

**Comment by Sharffffff** [comment]
Will do once I finish with my next big upgrade. Currently a bit busy with that and is very tired of coding to be honest. You can open a pull request for 1.18.2 branch, and I will add it, otherwise it will have to wait. 

Also, thank you! I had a lot of care for their design!

**Comment by Sharffffff** [comment]
Closed by accident
