### ISSUE TITLE
Convert curses to enchantments [Mod Compatibility]

### ISSUE THREAD

**Issue by sylenthuntress** [Sharffffff/Mantori#9]
The mantori:cursed_thorns, mantori:end_breaker, and mantori:shulkers_blessing enchantments are all listed as curses. This is both confusing in a visual sense (The curse's red color is meant to signify an enchantment is detrimental), and actively confuses compatibility with other mods that use curses and enchantments separately (e.g Biome Makeover's Altar mechanic).

Solution: Switch them all over to enchantments. The only downside I can think of is that said enchantments can be removed with a grindstone if you're unable to prevent that through other methods.

**Comment by Sharffffff** [comment]
They're all curses for a reason, to signify that they cannot be removed and that they will stop you from enchanting the armor on the enchanting table. And, if you ask people, Thorns can be considered a curse as is. 
Yes, mostly these enchantments have positive meaning, but they are contained only to these tools and cannot be obtained in any other way, and if there is a mod that makes them available in any other way, it makes the chitin armor and tools detrimental and is against my vision for them.
